/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  Auth: {
    region: "us-east-2",
    userPoolId: "us-east-2_oC4p6O7PS",
    userPoolWebClientId: "4nan7212tljtdmdjvp7e5ffmti",
  },
};

export default awsmobile;
